const cardImage = require("../../assets/images/kanva-series/card-image.jpg");

export const cardData = [
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "Check Open Sea",
    minted: "8000 Minted",
    left: "Sold out",
    isSoldOut: true,
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "Buy(1 PLTE)",
    isReadyForBuy: true,
    minted: "8000 Minted",
    left: "2000 Left",
  },

  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
  {
    cardImage,
    name: "albert einstein common",
    commonText: "Common / Common / Common",
    buttonText: "You need 1 PLTE",
    minted: "8000 Minted",
    left: "2000 Left",
  },
];
